name = "EngiQueers Concordia Fall 2026"
author = "VP IT"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcffa80b1b0271ae481c3095726f94faca2f574aebebdb819737c4c047869f5a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
