name = "EngiQueers Concordia Fall 2026"
author = "VP IT"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02a7f2fe3f7a30c94f6e17c9bc6fe1c72547fd75f90617b4aac906f3cf99b5e3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
